val acaciaBambooChime = <betterwithmods:bamboo_chime:4>;
val acaciaGrate = <betterwithmods:grate:4>;
val acaciaMetalChime = <betterwithmods:metal_chime:4>;
val acaciaMoulding = <betterwithmods:moulding_wood>.withTag({texture: {Name: "tfc:wood/planks/acacia"}});
val acaciaSlabOre = <ore:slabWoodAcacia>;
val acaciaSlats = <betterwithmods:slats:4>;
val archimedesScrew = <betterwithmods:material:24>;
val birchBambooChime = <betterwithmods:bamboo_chime:2>;
val birchGrate = <betterwithmods:grate:2>;
val birchMetalChime = <betterwithmods:metal_chime:2>;
val birchMoulding = <betterwithmods:moulding_wood>.withTag({texture: {Name: "tfc:wood/planks/birch"}});
val birchSlabOre = <ore:slabWoodBirch>;
val birchSlats = <betterwithmods:slats:2>;
val bwmAcaciaBench = <betterwithmods:wood_bench:4>;
val bwmAcaciaTable = <betterwithmods:wood_table:4>;
val bwmBirchBench = <betterwithmods:wood_bench:2>;
val bwmBirchTable = <betterwithmods:wood_table:2>;
val bwmCauldron = <betterwithmods:cooking_pot:1>;
val bwmLeatherBelt = <betterwithmods:material:9>;
val bwmOakBench = <betterwithmods:wood_bench>;
val bwmOakTable = <betterwithmods:wood_table>;
val bwmRope = <betterwithmods:rope>;
val bwmSpruceBench = <betterwithmods:wood_bench:1>;
val bwmSpruceTable = <betterwithmods:wood_table:1>;
val bwmWoodenGear = <betterwithmods:material>;
val candle = <ore:blockCandle>;
val carrot = <tfc:food/carrot>;
val coalDust = <ore:dustCoal>;
val cookedBeef = <tfc:food/cooked_beef>;
val cookedPork = <tfc:food/cooked_pork>;
val copperInductor = <tfctech:metal/copper_inductor>;
val copperPlate = <ore:plateCopper>;
val doubleIronSheet = <ore:sheetDoubleWroughtIron>;
val egg = <minecraft:egg>;
val enderOcular = <betterwithmods:material:40>;
val explosiveFuse = <betterwithmods:material:28>;
val flour = <ore:flour>;
val gemNormal = <ore:gemNormal>;
val glassBlock = <ore:blockGlass>;
val goldNugget = <ore:nuggetGold>;
val goldPlate = <ore:plateGold>;
val goldStrip = <tfctech:metal/gold_strip>;
val goldTrapdoor = <tfc:metal/trapdoor/gold>;
val graphiteDust = <ore:dustGraphite>;
val gunpowder = <minecraft:gunpowder>;
val ironIngot = <ore:ingotIron>;
val leather = <ore:leather>;
val leatherStrap = <betterwithmods:material:8>;
val lumber = <ore:lumber>;
val mushroom = <ore:mushroombrown>;
val oakBambooChime = <betterwithmods:bamboo_chime>;
val oakGrate = <betterwithmods:grate>;
val oakMetalChime = <betterwithmods:metal_chime>;
val oakMoulding = <betterwithmods:moulding_wood>.withTag({texture: {Name: "tfc:wood/planks/oak"}});
val oakSlabOre = <ore:slabWoodOak>;
val oakSlats = <betterwithmods:slats>;
val paper = <ore:paper>;
val planks = <ore:plankWood>;
val potato = <tfc:food/potato>;
val pulley = <betterwithmods:single_machine:1>;
val rawApplePie = <betterwithmods:raw_pastry:4>;
val redstoneDust = <ore:dustRedstone>;
val redstoneLatch = <betterwithmods:material:34>;
val reeds = <minecraft:reeds>;
val saltpetreDust = <ore:dustSaltpeter>;
val silverPlate = <ore:plateSilver>;
val spruceBambooChime = <betterwithmods:bamboo_chime:1>;
val spruceGrate = <betterwithmods:grate:1>;
val spruceMetalChime = <betterwithmods:metal_chime:1>;
val spruceMoulding = <betterwithmods:moulding_wood>.withTag({texture: {Name: "tfc:wood/planks/spruce"}});
val spruceSlabOre = <ore:slabWoodSpruce>;
val spruceSlats = <betterwithmods:slats:1>;
val stick = <ore:stickWood>;
val stone = <ore:stone>;
val strings = <ore:string>;
val sugar = <minecraft:sugar>;
val sulfurDust = <ore:dustSulfur>;
val tfcLeatherBelt = <tfctech:wiredraw/leather_belt>;
val tfcSugarcane = <tfc:food/sugarcane>;
val wireDrawBench = <tfctech:wire_draw_bench>;
val woodenAxle = <betterwithmods:wooden_axle>;
val woodenGear = <ore:gearWood>;
val woodenPressurePlateOre = <ore:pressurePlateWood>;
val wool = <minecraft:wool>;
val wroughtIronIngot = <ore:ingotWroughtIron>;
val wroughtIronRod = <ore:rodWroughtIron>;
val wroughtIronStrip = <ore:stripWroughtIron>;

recipes.remove(<betterwithmods:bamboo_chime:*>);
recipes.remove(<betterwithmods:bellows>);
recipes.remove(<betterwithmods:breeding_harness>);
recipes.remove(<betterwithmods:dynamite>);
recipes.remove(<betterwithmods:metal_chime:*>);
recipes.remove(bwmWoodenGear);
recipes.remove(leatherStrap);
recipes.removeByRecipeName("betterwithmods:blocks/grate_0");
recipes.removeByRecipeName("betterwithmods:blocks/grate_1");
recipes.removeByRecipeName("betterwithmods:blocks/grate_2");
recipes.removeByRecipeName("betterwithmods:blocks/grate_3");
recipes.removeByRecipeName("betterwithmods:blocks/grate_4");
recipes.removeByRecipeName("betterwithmods:blocks/grate_5");
recipes.removeByRecipeName("betterwithmods:blocks/mech/axle");
recipes.removeByRecipeName("betterwithmods:blocks/mech/saw");
recipes.removeByRecipeName("betterwithmods:blocks/mini/wood_bench_0");
recipes.removeByRecipeName("betterwithmods:blocks/mini/wood_bench_1");
recipes.removeByRecipeName("betterwithmods:blocks/mini/wood_bench_2");
recipes.removeByRecipeName("betterwithmods:blocks/mini/wood_bench_3");
recipes.removeByRecipeName("betterwithmods:blocks/mini/wood_bench_4");
recipes.removeByRecipeName("betterwithmods:blocks/mini/wood_bench_5");
recipes.removeByRecipeName("betterwithmods:blocks/mini/wood_table_0");
recipes.removeByRecipeName("betterwithmods:blocks/mini/wood_table_1");
recipes.removeByRecipeName("betterwithmods:blocks/mini/wood_table_2");
recipes.removeByRecipeName("betterwithmods:blocks/mini/wood_table_3");
recipes.removeByRecipeName("betterwithmods:blocks/mini/wood_table_4");
recipes.removeByRecipeName("betterwithmods:blocks/mini/wood_table_5");
recipes.removeByRecipeName("betterwithmods:blocks/redstone/detector_rail_wood");
recipes.removeByRecipeName("betterwithmods:blocks/redstone/hibachi");
recipes.removeByRecipeName("betterwithmods:blocks/redstone/lens");
recipes.removeByRecipeName("betterwithmods:blocks/slats_0");
recipes.removeByRecipeName("betterwithmods:blocks/slats_1");
recipes.removeByRecipeName("betterwithmods:blocks/slats_2");
recipes.removeByRecipeName("betterwithmods:blocks/slats_3");
recipes.removeByRecipeName("betterwithmods:blocks/slats_4");
recipes.removeByRecipeName("betterwithmods:blocks/slats_5");
recipes.removeByRecipeName("betterwithmods:food/beef_dinner");
recipes.removeByRecipeName("betterwithmods:food/beef_potatoes");
recipes.removeByRecipeName("betterwithmods:food/ham_and_eggs");
recipes.removeByRecipeName("betterwithmods:food/pork_dinner");
recipes.removeByRecipeName("betterwithmods:food/raw_kebab");
recipes.removeByRecipeName("betterwithmods:food/raw_omelet");
recipes.removeByRecipeName("betterwithmods:food/raw_pastry_0");
recipes.removeByRecipeName("betterwithmods:food/raw_pastry_2");
recipes.removeByRecipeName("betterwithmods:food/raw_pastry_4");
recipes.removeByRecipeName("betterwithmods:food/raw_scrambled_egg");
recipes.removeByRecipeName("betterwithmods:food/tasty_sandwich");
recipes.removeByRecipeName("betterwithmods:items/material/material.ender_ocular");
recipes.removeByRecipeName("betterwithmods:items/material/material.hemp_cloth");
recipes.removeByRecipeName("betterwithmods:items/material/material.leather_belt");
recipes.removeByRecipeName("betterwithmods:items/material/material.screw");
recipes.removeByRecipeName("betterwithmods:items/stump_remover");

recipes.addShaped("acacia_bamboo_chime", acaciaBambooChime, [[null, strings, null], [strings, woodenPressurePlateOre, strings], [tfcSugarcane, acaciaMoulding, tfcSugarcane]]);
recipes.addShaped("acacia_grate", acaciaGrate * 4, [[acaciaMoulding, stick, acaciaMoulding], [acaciaMoulding, stick, acaciaMoulding]]);
recipes.addShaped("acacia_metal_chime", acaciaMetalChime, [[null, strings, null], [strings, woodenPressurePlateOre, strings], [ironIngot, acaciaMoulding, ironIngot]]);
recipes.addShaped("acacia_slats", acaciaSlats * 4, [[acaciaMoulding, acaciaMoulding], [acaciaMoulding, acaciaMoulding]]);
recipes.addShaped("arch_screw_iron", archimedesScrew, [[wroughtIronStrip, wroughtIronRod, wroughtIronStrip], [wroughtIronStrip, wroughtIronRod, wroughtIronStrip]]);
recipes.addShaped("bellows", <betterwithmods:bellows>, [[lumber, lumber, lumber], [leather, leather, leather], [bwmLeatherBelt, woodenGear, bwmLeatherBelt]]);
recipes.addShaped("birch_bamboo_chime", birchBambooChime, [[null, strings, null], [strings, woodenPressurePlateOre, strings], [tfcSugarcane, birchMoulding, tfcSugarcane]]);
recipes.addShaped("birch_grate", birchGrate * 4, [[birchMoulding, stick, birchMoulding], [birchMoulding, stick, birchMoulding]]);
recipes.addShaped("birch_metal_chime", birchMetalChime, [[null, strings, null], [strings, woodenPressurePlateOre, strings], [ironIngot, birchMoulding, ironIngot]]);
recipes.addShaped("birch_slats", birchSlats * 4, [[birchMoulding, birchMoulding], [birchMoulding, birchMoulding]]);
recipes.addShaped("bwm_acacia_bench", bwmAcaciaBench * 4, [[acaciaSlabOre, acaciaSlabOre, acaciaSlabOre], [null, acaciaMoulding, null]]);
recipes.addShaped("bwm_acacia_table", bwmAcaciaTable * 4, [[acaciaSlabOre, acaciaSlabOre, acaciaSlabOre], [null, acaciaMoulding, null], [null, acaciaMoulding, null]]);
recipes.addShaped("bwm_birch_bench", bwmBirchBench * 4, [[birchSlabOre, birchSlabOre, birchSlabOre], [null, birchMoulding, null]]);
recipes.addShaped("bwm_birch_table", bwmBirchTable * 4, [[birchSlabOre, birchSlabOre, birchSlabOre], [null, birchMoulding, null], [null, birchMoulding, null]]);
recipes.addShaped("bwm_hibachi", <betterwithmods:hibachi>, [[copperPlate, copperPlate, copperPlate], [stone, copperInductor, stone], [stone, redstoneDust, stone]]);
recipes.addShaped("bwm_leather_belt", bwmLeatherBelt * 2, [[null, tfcLeatherBelt, null], [tfcLeatherBelt, null, tfcLeatherBelt], [null, tfcLeatherBelt, null]]);
recipes.addShaped("bwm_lens", <betterwithmods:lens>, [[goldPlate, glassBlock, goldPlate], [goldPlate, gemNormal, goldPlate], [goldPlate, silverPlate, goldPlate]]);
recipes.addShaped("bwm_oak_bench", bwmOakBench * 4, [[oakSlabOre, oakSlabOre, oakSlabOre], [null, oakMoulding, null]]);
recipes.addShaped("bwm_oak_table", bwmOakTable * 4, [[oakSlabOre, oakSlabOre, oakSlabOre], [null, oakMoulding, null], [null, oakMoulding, null]]);
recipes.addShaped("bwm_saw",  <betterwithmods:saw>, [[null, doubleIronSheet, null], [woodenGear, bwmLeatherBelt, woodenGear], [lumber, woodenGear, lumber]]);
recipes.addShaped("bwm_spruce_bench", bwmSpruceBench * 4, [[spruceSlabOre, spruceSlabOre, spruceSlabOre], [null, spruceMoulding, null]]);
recipes.addShaped("bwm_spruce_table", bwmSpruceTable * 4, [[spruceSlabOre, spruceSlabOre, spruceSlabOre], [null, spruceMoulding, null], [null, spruceMoulding, null]]);
recipes.addShaped("candle_holder", <betterwithmods:candle_holder>, [[wroughtIronRod], [wroughtIronIngot]]);
recipes.addShaped("dynamite", <betterwithmods:dynamite>, [[explosiveFuse, null, null], [gunpowder, gunpowder, gunpowder], [paper, paper, paper]]);
recipes.addShaped("ender_ocular", enderOcular, [[null, goldStrip, null], [goldStrip, <minecraft:ender_pearl>, goldStrip], [null, goldStrip, null]]);
recipes.addShaped("oak_bamboo_chime", oakBambooChime, [[null, strings, null], [strings, woodenPressurePlateOre, strings], [tfcSugarcane, oakMoulding, tfcSugarcane]]);
recipes.addShaped("oak_grate", oakGrate * 4, [[oakMoulding, stick, oakMoulding], [oakMoulding, stick, oakMoulding]]);
recipes.addShaped("oak_metal_chime", oakMetalChime, [[null, strings, null], [strings, woodenPressurePlateOre, strings], [ironIngot, oakMoulding, ironIngot]]);
recipes.addShaped("oak_slats", oakSlats * 4, [[oakMoulding, oakMoulding], [oakMoulding, oakMoulding]]);
recipes.addShaped("spruce_bamboo_chime", spruceBambooChime, [[null, strings, null], [strings, woodenPressurePlateOre, strings], [tfcSugarcane, spruceMoulding, tfcSugarcane]]);
recipes.addShaped("spruce_grate", spruceGrate * 4, [[spruceMoulding, stick, spruceMoulding], [spruceMoulding, stick, spruceMoulding]]);
recipes.addShaped("spruce_metal_chime", spruceMetalChime, [[null, strings, null], [strings, woodenPressurePlateOre, strings], [ironIngot, spruceMoulding, ironIngot]]);
recipes.addShaped("spruce_slats", spruceSlats * 4, [[spruceMoulding, spruceMoulding], [spruceMoulding, spruceMoulding]]);
recipes.addShaped("wooden_axle_leather", woodenAxle, [[lumber], [bwmLeatherBelt], [lumber]]);
recipes.addShaped("wooden_axle_rope", woodenAxle, [[lumber], [bwmRope], [lumber]]);
recipes.addShapeless("beef_dinner", <betterwithmods:beef_dinner> * 3, [cookedBeef, potato, carrot]);
recipes.addShapeless("beef_potato", <betterwithmods:beef_potatoes> * 2, [cookedBeef, potato]);
recipes.addShapeless("bwm_cauldron", <betterwithmods:cooking_pot:1>, [<minecraft:cauldron>]);
recipes.addShapeless("cookie_dough", <betterwithmods:raw_pastry:2> * 2, [<ore:categoryFruit>, <minecraft:sugar>, <ore:categoryDough>]);
recipes.addShapeless("ham_and_eggs", <betterwithmods:ham_and_eggs> * 2, [<tfc:food/cooked_egg>, cookedPork]);
recipes.addShapeless("leather_strap", leatherStrap * 3, [leather, <ore:knife>.transformDamage()]);
recipes.addShapeless("pork_dinner", <betterwithmods:pork_dinner> * 3, [cookedPork, carrot, potato]);
recipes.addShapeless("raw_apple_pie", rawApplePie, [<ore:apple>, sugar, flour, egg]);
recipes.addShapeless("raw_kebab", <betterwithmods:raw_kebab> * 3, [stick, mushroom, carrot, <tfc:food/mutton>]);
recipes.addShapeless("raw_omelet", <betterwithmods:raw_omelet> * 2, [egg, mushroom, mushroom, mushroom]);
recipes.addShapeless("raw_scrambled_eggs", <betterwithmods:raw_scrambled_egg>, [egg, <tfc:wooden_bucket>.withTag({Fluid: {FluidName: "milk", Amount: 1000}}).transformReplace(<tfc:wooden_bucket>) | <minecraft:milk_bucket>.transformReplace(<minecraft:bucket>)]);
recipes.addShapeless("wooden_gear", bwmWoodenGear, [<ore:chisel>.transformDamage(), lumber]);

recipes.replaceAllOccurences(<betterwithmods:material:14>, <tfc:metal/double_ingot/soulforged_steel>, <betterwithmods:steel_anvil>);
recipes.replaceAllOccurences(<betterwithmods:raw_egg>, <minecraft:egg>, <betterwithmods:raw_pastry:1>);
recipes.replaceAllOccurences(<betterwithmods:raw_pastry:3>, <ore:flour>, <betterwithmods:raw_pastry:1>);
recipes.replaceAllOccurences(<minecraft:bucket>, <ore:bucket>, <betterwithmods:bucket>);
recipes.replaceAllOccurences(<minecraft:pumpkin>, <firmalife:pumpkin_chunks>, <betterwithmods:raw_pastry:1>);
recipes.replaceAllOccurences(goldNugget, goldStrip, redstoneLatch);
recipes.replaceAllOccurences(ironIngot, wroughtIronRod, <betterwithmods:booster>);
recipes.replaceAllOccurences(ironIngot, wroughtIronRod, <betterwithmods:detector_rail_steel>);
recipes.replaceAllOccurences(ironIngot, wroughtIronRod, <betterwithmods:detector_rail_stone>);
recipes.replaceAllOccurences(planks, lumber, <betterwithmods:platform>);
recipes.replaceAllOccurences(planks, lumber, pulley);